export const CART_ADD_ITEM = 'CARD_ITEM_ADD'
export const CART_REMOVE_ITEM = 'CARD_REMOVE_ADD'
export const CART_ADD_FAIL = 'CARD_ADD_FAIL'

export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'
